spring:
  datasource:
    url: jdbc:h2:mem:pontuaweb_h2
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false